"""add course model

Revision ID: 1cf73d0a5fa7
Revises: 00dfd2e497a3
Create Date: 2025-11-06 14:44:00.302896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cf73d0a5fa7'
down_revision: Union[str, Sequence[str], None] = '00dfd2e497a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('classes_teacher_id_fkey'), 'classes', type_='foreignkey')
    op.drop_column('classes', 'teacher_id')
    op.drop_column('classes', 'room')
    op.drop_column('classes', 'end_time')
    op.drop_column('classes', 'present_window_minutes')
    op.drop_column('classes', 'late_window_minutes')
    op.drop_column('classes', 'start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('classes', sa.Column('late_window_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('classes', sa.Column('present_window_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('classes', sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('classes', sa.Column('room', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('classes', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('classes_teacher_id_fkey'), 'classes', 'users', ['teacher_id'], ['id'])
    op.drop_table('courses')
    # ### end Alembic commands ###
