"""add start_date and end_date to courses

Revision ID: 4d98fef3c929
Revises: 7b48b29e9c37
Create Date: 2025-11-17 13:22:18.639927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d98fef3c929'
down_revision: Union[str, Sequence[str], None] = '7b48b29e9c37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('target_audience', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_announcement_active', 'announcements', ['is_active'], unique=False)
    op.create_index('idx_announcement_created', 'announcements', ['created_at'], unique=False)
    op.create_index('idx_announcement_target', 'announcements', ['target_audience'], unique=False)
    op.create_table('parent_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'student_id', name='unique_parent_student')
    )
    op.create_index('idx_parent_student_parent', 'parent_students', ['parent_id'], unique=False)
    op.create_index('idx_parent_student_student', 'parent_students', ['student_id'], unique=False)
    op.create_table('attendance_appeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['attendance_records.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_appeal_created', 'attendance_appeals', ['created_at'], unique=False)
    op.create_index('idx_appeal_status', 'attendance_appeals', ['status'], unique=False)
    op.create_index('idx_appeal_student', 'attendance_appeals', ['student_id'], unique=False)
    op.add_column('courses', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('courses', sa.Column('end_date', sa.Date(), nullable=False))
    op.add_column('users', sa.Column('gender', sa.String(length=1), nullable=True))
    op.add_column('users', sa.Column('degree_level', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('start_year', sa.String(length=4), nullable=True))
    op.drop_column('users', 'grade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('grade', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('users', 'start_year')
    op.drop_column('users', 'degree_level')
    op.drop_column('users', 'gender')
    op.drop_column('courses', 'end_date')
    op.drop_column('courses', 'start_date')
    op.drop_index('idx_appeal_student', table_name='attendance_appeals')
    op.drop_index('idx_appeal_status', table_name='attendance_appeals')
    op.drop_index('idx_appeal_created', table_name='attendance_appeals')
    op.drop_table('attendance_appeals')
    op.drop_index('idx_parent_student_student', table_name='parent_students')
    op.drop_index('idx_parent_student_parent', table_name='parent_students')
    op.drop_table('parent_students')
    op.drop_index('idx_announcement_target', table_name='announcements')
    op.drop_index('idx_announcement_created', table_name='announcements')
    op.drop_index('idx_announcement_active', table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
