"""Add database constraints and indexes for performance optimization

Revision ID: 7b48b29e9c37
Revises: 1cf73d0a5fa7
Create Date: 2025-11-16 13:53:57.871573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b48b29e9c37'
down_revision: Union[str, Sequence[str], None] = '1cf73d0a5fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance_records', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attendance_records', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attendance_records', 'manual_override',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index('idx_record_detected_at', 'attendance_records', ['detected_at'], unique=False)
    op.create_index('idx_record_session_student', 'attendance_records', ['session_id', 'student_id'], unique=False)
    op.create_index('idx_record_status', 'attendance_records', ['status'], unique=False)
    op.create_unique_constraint('unique_session_student', 'attendance_records', ['session_id', 'student_id'])
    op.add_column('attendance_sessions', sa.Column('present_window_minutes', sa.Integer(), nullable=False))
    op.add_column('attendance_sessions', sa.Column('late_window_minutes', sa.Integer(), nullable=False))
    op.alter_column('attendance_sessions', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attendance_sessions', 'status',
               existing_type=postgresql.ENUM('SCHEDULED', 'ACTIVE', 'COMPLETED', name='sessionstatus'),
               nullable=False)
    op.create_index('idx_session_class_date', 'attendance_sessions', ['class_id', 'session_date'], unique=False)
    op.create_index('idx_session_status', 'attendance_sessions', ['status'], unique=False)
    op.alter_column('courses', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('courses', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('courses', 'day_of_week',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_course_class_teacher', 'courses', ['class_id', 'teacher_id'], unique=False)
    op.create_index('idx_course_day_time', 'courses', ['day_of_week', 'start_time', 'end_time'], unique=False)
    op.alter_column('face_encodings', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_encoding_student', 'face_encodings', ['student_id'], unique=False)
    op.create_unique_constraint('unique_student_encoding', 'face_encodings', ['student_id'])
    op.alter_column('system_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('system_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index('idx_log_action', 'system_logs', ['action'], unique=False)
    op.create_index('idx_log_timestamp', 'system_logs', ['timestamp'], unique=False)
    op.create_index('idx_log_user_timestamp', 'system_logs', ['user_id', 'timestamp'], unique=False)
    op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('nationality', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('major', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('grade', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('courses', sa.JSON(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_role', 'users', ['role'], unique=False)
    op.create_index('idx_user_username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_username', table_name='users')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('users', 'courses')
    op.drop_column('users', 'grade')
    op.drop_column('users', 'major')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'nationality')
    op.drop_column('users', 'full_name')
    op.drop_index('idx_log_user_timestamp', table_name='system_logs')
    op.drop_index('idx_log_timestamp', table_name='system_logs')
    op.drop_index('idx_log_action', table_name='system_logs')
    op.alter_column('system_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('system_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('unique_student_encoding', 'face_encodings', type_='unique')
    op.drop_index('idx_encoding_student', table_name='face_encodings')
    op.alter_column('face_encodings', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('idx_course_day_time', table_name='courses')
    op.drop_index('idx_course_class_teacher', table_name='courses')
    op.alter_column('courses', 'day_of_week',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('idx_session_status', table_name='attendance_sessions')
    op.drop_index('idx_session_class_date', table_name='attendance_sessions')
    op.alter_column('attendance_sessions', 'status',
               existing_type=postgresql.ENUM('SCHEDULED', 'ACTIVE', 'COMPLETED', name='sessionstatus'),
               nullable=True)
    op.alter_column('attendance_sessions', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('attendance_sessions', 'late_window_minutes')
    op.drop_column('attendance_sessions', 'present_window_minutes')
    op.drop_constraint('unique_session_student', 'attendance_records', type_='unique')
    op.drop_index('idx_record_status', table_name='attendance_records')
    op.drop_index('idx_record_session_student', table_name='attendance_records')
    op.drop_index('idx_record_detected_at', table_name='attendance_records')
    op.alter_column('attendance_records', 'manual_override',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('attendance_records', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('attendance_records', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
