"""Add auto_end_time column to attendance_sessions

Revision ID: b38d3f2223a2
Revises: 4d98fef3c929
Create Date: 2025-11-27 14:09:45.194507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38d3f2223a2'
down_revision: Union[str, Sequence[str], None] = '4d98fef3c929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_sessions', sa.Column('auto_end_time', sa.Time(), nullable=True))
    op.alter_column('courses', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('courses', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('courses', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('attendance_sessions', 'auto_end_time')
    # ### end Alembic commands ###
